version: "3.8"
services:

  rabbitmq:
    image: rabbitmq:3.10-management
    environment:
      RABBITMQ_DEFAULT_USER: "my_user"
      RABBITMQ_DEFAULT_PASS: "my_password"
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  app:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    environment:
      PYTHONPATH: .:app
      DEBUG: 1
    ports:
      - "8383:8000"
    command: bash ./app/start.sh
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    restart: on-failure

  consumer:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ./
      dockerfile: ./consumer/Dockerfile
    environment:
      PYTHONPATH: .:consumer
    command: bash ./consumer/start.sh
    links:
      - rabbitmq
    volumes:
      - ./models:/home/models
    depends_on:
      - rabbitmq
    restart: on-failure
